DisqusShortname = ""
MetaDataFormat = "yaml"
baseURL = "https://www.stidsirnarasa.ac.id/"
googleAnalytics = ""
languageCode = "id-id"
title = "Sekolah Tinggi Ilmu Dakwah Sirnarasa"
theme = "stid"

[[menu.main]]
name = "Jadwal Perkuliahan"
parent = "Program Studi"
weight = 3
[[menu.main]]
name = "Jamiatul Quro"
parent = "UKM"
url = "#"
weight = 6
[[menu.main]]
name = "Futsal"
parent = "UKM"
url = "#"
weight = 5
[[menu.main]]
name = "Pramuka"
parent = "UKM"
url = "#"
weight = 4
[[menu.main]]
name = "Bahasa"
parent = "UKM"
url = "#"
weight = 3
[[menu.main]]
name = "Masalika"
parent = "UKM"
url = "#"
weight = 2
[[menu.main]]
name = "Jurnalistik"
parent = "UKM"
url = "#"
weight = 1
[[menu.main]]
name = "UKM"
url = "https://ukm.stidsirnarasa.ac.id/"
weight = 4
[[menu.main]]
name = "Publikasi"
url = "/post/"
weight = 3
[[menu.main]]
name = "Program Studi"
url = "/program-studi/"
weight = 2
[[menu.main]]
name = "Akademik"
url = "/akademik/"
weight = 1
