DisqusShortname = ""
MetaDataFormat = "yaml"
baseURL = "https://www.stidsirnarasa.ac.id/"
description = "Terwujudnya Perguruan Tinggi Dakwah berbasis riset dalam membentuk manusia yang sempurna (Insan Kamil) melalui pendidikan, penelitian, pengabdian yang berlandaskan nilai-nilai sufistik. "
googleAnalytics = ""
languageCode = "id-id"
title = "Sekolah Tinggi Ilmu Dakwah Sirnarasa"
[[menu.main]]
name = "Publikasi"
url = "/post/"
weight = 3
[[menu.main]]
name = "Program Studi"
url = "/program-studi/"
weight = 2
[[menu.main]]
name = "Akademik"
url = "/akademik/"
weight = 1
