DisqusShortname = ""
MetaDataFormat = "yaml"
baseURL = "https://www.stidsirnarasa.ac.id/"
googleAnalytics = "UA-92294913-1"
languageCode = "id-id"
theme = "boomerang"
title = "STID Sirnarasa"
[[menu.main]]
name = "UKM"
parent = "Kemahasiswaan"
url = "https://ukm.stidsirnarasa.ac.id/"
weight = 1
[[menu.main]]
name = "Jamiatul Quro"
parent = "UKM"
url = "#"
weight = 6
[[menu.main]]
name = "Futsal"
parent = "UKM"
url = "#"
weight = 5
[[menu.main]]
name = "Pramuka"
parent = "UKM"
url = "#"
weight = 4
[[menu.main]]
name = "Jadwal Perkuliahan"
parent = "Program Studi"
weight = 3
[[menu.main]]
name = "Bahasa"
parent = "UKM"
url = "#"
weight = 3
[[menu.main]]
name = "Masalika"
parent = "UKM"
url = "#"
weight = 2
[[menu.main]]
name = "Jurnalistik"
parent = "UKM"
url = "http://jurnalistik.stidsirnarasa.ac.id"
weight = 1
[[menu.main]]
name = "Publikasi"
url = "/post/"
weight = 3
[[menu.main]]
name = "Program Studi"
url = "/program-studi/"
weight = 2
[[menu.main]]
name = "Akademik"
url = "/akademik/"
weight = 1
[params]
footerTxt = "Terwujudnya Perguruan Tinggi Dakwah berbasis *riset* dalam membentuk Manusia yang sempurna (Insan Kamil) melalui Pendidikan, Penelitian, Pengabdian yang berlandaskan nilai-nilai Sufistik."
