baseURL = "https://www.stidsirnarasa.ac.id/"
languageCode = "id-id"
title = "Sekolah Tinggi Ilmu Dakwah Sirnarasa"
description = "Sekolah Tinggi Ilmu Dakwah Sirnarasa, Cisirri. Kampus Peradaban, Profesional Berakhlakul Karimah, Pesantren Mahasiswa Terpadu."
image = "/img/graduation.jpg"
