---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
  templates:
  - new-post
- type: directory
  path: content/informasi
  label: Informasi
  create: all
  match: "**/*"
  templates:
  - pengumuman
- type: directory
  path: content/event
  label: Acara & Kegiatan
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: content
  label: Halaman
  create: all
  match: "*"
  templates:
  - halaman
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
